(new) Oop practice
valeriaDD/laravel_project pull request #10
Opened 2022-01-20 21:10 UTC by valeriaDD

2022-01-25 18:55 UTC, egorbwork requested changes
I can't approve for the moments loggers.

2022-01-25 18:55 UTC, egorbwork commented on app/Services/ProductionRequestActivityLogger.php
> +            'email' => $request->email,
Production logger should not contain the request data.

2022-01-25 18:55 UTC, egorbwork commented on app/Services/DebugRequestActivityLogger.php
> +            'email' => $request->email,
If you want to keep request data in the debug logger, you should keep everything under single key.

2022-01-26 21:01 UTC, valeriaDD commented on app/Services/DebugRequestActivityLogger.php
> +            'email' => $request->email,
Changed - request data is collected under the same key and other info about request is collected

2022-01-26 21:01 UTC, valeriaDD commented on app/Services/ProductionRequestActivityLogger.php
> +            'email' => $request->email,
Changed - request data is erased and collected the fingerprint instead

2022-01-27 11:06 UTC, egorbwork approved these changes
Now looks acceptable.

2022-01-30 11:39 UTC, merged