Create Models (Version without Migrations)
valeriaDD/laravel_project pull request #3
Opened 2021-12-13 23:34 UTC by valeriaDD

2021-12-20 10:03 UTC, vistrati commented
`Schedule` table is missing in your models

2021-12-20 10:03 UTC, vistrati requested changes

2021-12-20 10:03 UTC, vistrati commented on app/Models/Kinetotherapeut.php
> +    public function appointment(){
`appointments`

2021-12-20 10:03 UTC, vistrati commented on app/Models/Day.php
> +        return $this->belongsTo(WorkingDay::class, 'id', 'day_id');
here you should use direct relation `hasOne` and in WorkinDay inverse, please take a look at `Kinetotherapeut` model how you did for address

2021-12-20 10:03 UTC, vistrati commented on app/Models/Service.php
> +    public function appointment(){
`appointments`

2021-12-20 10:03 UTC, vistrati commented on app/Models/WorkingDay.php
> +        return $this->hasMany(Day::class, 'day_id');
here you should use `belongsTo` and in `Day` has many.

2021-12-21 21:35 UTC, valeriaDD commented on app/Models/Address.php
> +    protected function kinetotherapeut (){
Fixed - made the function public

2021-12-21 21:35 UTC, valeriaDD commented on app/Models/Client.php
> +    public function appointment(){
Fixed - changed the name to 'appointments'

2021-12-21 21:39 UTC, valeriaDD commented on app/Models/Day.php
> +        return $this->belongsTo(WorkingDay::class, 'id', 'day_id');
Fixed- made a direct relation between days and working days

2021-12-21 21:39 UTC, valeriaDD commented on app/Models/Kinetotherapeut.php
> +    public function appointment(){
Fixed - changed naming to appointments

2021-12-21 21:39 UTC, valeriaDD commented on app/Models/Service.php
> +    public function appointment(){
Fixed - changed naming to appointments

2021-12-21 21:40 UTC, valeriaDD commented on app/Models/WorkingDay.php
> +        return $this->hasMany(Day::class, 'day_id');
Fixed - changed this relation to direct one

2021-12-21 21:42 UTC, valeriaDD commented
> `Schedule` table is missing in your models



> 

Tried to implement it - but I'm not sure how correct it is - can you take a look one more time?

2022-01-18 16:46 UTC, merged