Mailing
valeriaDD/laravel_project pull request #4
Opened 2022-01-10 16:58 UTC by valeriaDD

2022-01-13 07:40 UTC, egorbwork requested changes
Looks nice, but still a bit incomplete.

2022-01-13 07:40 UTC, egorbwork commented on resources/views/Emails/ContactUs.blade.php
> +        user name : {{ $name }}
Gender is not used here

2022-01-13 07:40 UTC, egorbwork commented on app/Http/Controllers/ContactsController.php
> +                        'messageText' => $data['messageText']
if you keep the name of input like messageText you should just use `$data` here.

2022-01-18 13:46 UTC, valeriaDD commented on resources/views/Emails/ContactUs.blade.php
> +        user name : {{ $name }}
fixed - added information about the gender as well

2022-01-18 13:48 UTC, valeriaDD commented on app/Http/Controllers/ContactsController.php
> +                        'messageText' => $data['messageText']
Fixed, accessed directly the data - without fracturing it

2022-01-18 18:03 UTC, egorbwork approved these changes
This part is ready. You can merge it after solving conflicts.

2022-01-20 12:03 UTC, merged