OOP-design-principles
valeriaDD/laravel_project pull request #9
Opened 2022-01-20 12:53 UTC by valeriaDD

2022-01-20 17:36 UTC, egorbwork requested changes
For the moment this pr is not compatible with requirements.

2022-01-20 17:36 UTC, egorbwork commented on app/Console/Commands/CacheTestingCommand.php
> +        $res = $this->ask(
I do not recommend to use abbreviations.

2022-01-20 17:36 UTC, egorbwork commented on app/Providers/AppServiceProvider.php
> +            if (\App::environment() == "local"){
My request was to use for production, if I will set environment testing it will use Production, that is not acceptable.

2022-01-20 17:36 UTC, egorbwork commented on app/Console/Commands/RussianRouletteCommand.php
> +        $this->line("See todays statistic of deaths bellow:");
I requested separated command for statistics.

2022-01-20 17:36 UTC, egorbwork commented on app/Console/Commands/RussianRouletteCommand.php
> +        $randNr = rand(1,6);
Please also keep in statistic in which place it was.

2022-01-20 23:02 UTC, valeriaDD commented on app/Console/Commands/CacheTestingCommand.php
> +        $res = $this->ask(
Fixed - used log format of variables

2022-01-20 23:03 UTC, valeriaDD commented on app/Console/Commands/RussianRouletteCommand.php
> +        $this->line("See todays statistic of deaths bellow:");
Fixed - separated the game in RussianRoulleteCommand and RussianRoulleteStatisticCommand

2022-01-20 23:05 UTC, valeriaDD commented on app/Console/Commands/RussianRouletteCommand.php
> +        $randNr = rand(1,6);
Fixed - Made 2 types of statistics tracker - One that counts the nr of deaths for each player(Computer, Human) and a more detailed version that shows info about who started the game - where was the bullet located - who died

2022-01-20 23:13 UTC, valeriaDD commented on app/Providers/AppServiceProvider.php
> +            if (\App::environment() == "local"){
Fixed - made an (else if) statement instead of (else)

2022-01-24 09:09 UTC, egorbwork requested changes
Still not acceptable. Some places requires fixed.

2022-01-24 09:09 UTC, egorbwork commented on app/Console/Commands/RussianRouletteCommand.php
> +        $this->cacheRepository->set('Statistic', $statistic, 86400);
As it is collection of data, should be called `statistics`

2022-01-24 09:09 UTC, egorbwork commented on app/Console/Commands/RussianRouletteStatisticCommand.php
> +    protected $signature = 'russian-roulette-statistic';
For laravel code style, I would suggest: `russian-roulette:statistics`

2022-01-24 09:09 UTC, egorbwork commented on app/Console/Commands/RussianRouletteStatisticCommand.php
> +        $this->table(['Who Started', 'Bullet Place', "Who Died"], $detailedStatistic);
Instead I recommend how many times which number was. This is not statistic it is simple table.

2022-01-24 09:09 UTC, egorbwork commented on app/Providers/AppServiceProvider.php
> +            if ( strtolower(\App::environment()) == "local"){
So If I will have any environment different from local or production(example: testing, staging, etc.) application should fail?

2022-01-24 09:23 UTC, valeriaDD commented on app/Providers/AppServiceProvider.php
> +            if ( strtolower(\App::environment()) == "local"){
Fixed - else is thrown DummyRequestActivityLogger

2022-01-24 09:59 UTC, valeriaDD commented on app/Console/Commands/RussianRouletteStatisticCommand.php
> +    protected $signature = 'russian-roulette-statistic';
Fixed

2022-01-24 10:00 UTC, valeriaDD commented on app/Console/Commands/RussianRouletteCommand.php
> +            $this->line("Something is wrong");
Fixed

2022-01-24 10:00 UTC, valeriaDD commented on app/Console/Commands/RussianRouletteCommand.php
> +        // $this->line("See todays statistic of deaths bellow:");
Fixed

2022-01-24 10:00 UTC, valeriaDD commented on app/Console/Commands/RussianRouletteCommand.php
> +        $this->cacheRepository->set('Statistic', $statistic, 86400);
Fixed

2022-01-24 10:01 UTC, valeriaDD commented on app/Console/Commands/RussianRouletteStatisticCommand.php
> +        $this->table(['Who Started', 'Bullet Place', "Who Died"], $detailedStatistic);
Fixed - added a new table with statistics of bullet place

2022-01-24 10:12 UTC, valeriaDD commented on app/Console/Commands/RussianRouletteCommand.php
> +        $this->line("You will take turns playing with computer shuting in yourself");
Fixed - made a more descriptive rules

2022-01-25 20:08 UTC, egorbwork requested changes

2022-01-25 20:08 UTC, egorbwork commented on app/Providers/AppServiceProvider.php
> +            if ( strtolower(\App::environment()) == "local"){
It is not compatible with requirements.

2022-01-26 20:10 UTC, valeriaDD commented on app/Providers/AppServiceProvider.php
> +            if ( strtolower(\App::environment()) == "local"){
Changed - If environment is production - the ProductionRequestActivityLogger will be injected, in other cases the DebugRequestActivityLogger is injected

2022-01-27 11:23 UTC, egorbwork approved these changes
It is acceptable, but some moments, still could be improved.

2022-01-27 11:23 UTC, egorbwork commented on app/Console/Commands/RussianRouletteStatisticCommand.php
> +    protected $description = 'Command description';
A more adequate description is preferable.

2022-01-30 11:42 UTC, merged